name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/avatar.jpg
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf
